export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';

export const UPDATE_MESSAGE_STATUS_SUCCESS = 'UPDATE_MESSAGE_STATUS_SUCCESS';
export const UPDATE_MESSAGE_STATUS_ERROR = 'UPDATE_MESSAGE_STATUS_ERROR';
