module.exports = {
    LOAD_MESSAGES: 'LOAD_MESSAGES',
    LOAD_MESSAGES_SUCCESS: 'LOAD_MESSAGES_SUCCESS',
    LOAD_MESSAGES_ERROR: 'LOAD_MESSAGES_ERROR',

    UPDATE_MESSAGE_STATUS_SUCCESS: 'UPDATE_MESSAGE_STATUS_SUCCESS',
    UPDATE_MESSAGE_STATUS_ERROR: 'UPDATE_MESSAGE_STATUS_ERROR'
};
